src/Entity/Articles.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticlesRepository")
 */
class Articles
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $thumbnail_img;

    /**
     * @ORM\Column(type="date")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $views;

    /**
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="Article", cascade={"remove"})
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="articles")
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @Assert\Length(
     *      min = 10,
     *      max = 100,
     *      minMessage = "La description doit avoir minimum {{ limit }} caratères",
     *      maxMessage = "La description ne doit pas dépasser {{ limit }} caratères"
     * )
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getThumbnailImg()
    {
        return $this->thumbnail_img;
    }

    public function setThumbnailImg($thumbnail_img): self
    {
        $this->thumbnail_img = $thumbnail_img;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\Articles;
use App\Entity\Category;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('body', TextareaType::class, ['attr'=>[]])
            ->add('thumbnail_img', FileType::class,
                [
                    'constraints' => [
                        new File([
                            'mimeTypes' => [
                                'image/jpeg',
                                'image/png'
                            ],
                            'mimeTypesMessage' => 'Les images sont uniquement téléchargeables',
                        ])
                    ],
                    'required' => false,

                    'data_class'=>null,
                    'label'=>'Choisir une image','label_attr'=>['class'=>'text-light mb-0']
                ])
            ->add('title', TextType::class, ['attr'=>['class'=>'form-control']])
            ->add('description', TextType::class, ['attr'=>['class'=>'form-control']])
            ->add('Category', EntityType::class, ['class'=>Category::class, 'placeholder'=>'Choisissez une catégorie','choice_label'=>'name', 'attr'=>['class'=>'form-control']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }
}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("adminDashboard/articles")
 */
class ArticlesController extends AbstractController
{
    /**
     * @Route("/", name="articles_index", methods={"GET"})
     */
    public function index(ArticlesRepository $articlesRepository): Response
    {
        return $this->render('articles/index.html.twig', [
            'articles' => $articlesRepository->findAll(),
        ]);
    }


    /**
     * @Route("/new", name="articles_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Articles();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);




        if ($form->isSubmitted() && $form->isValid()) {
            $img = $article->getThumbnailImg();

            if($img)
            {
                $newfn = $img->getClientOriginalName();
                $fs = new Filesystem();
                if($fs->exists($this->getParameter('bibliotheque').'/'.$img)){
                    $article->setThumbnailImg($newfn);
                }
                else{
                    try {
                        $img->move(
                            $this->getParameter('bibliotheque'),
                            $newfn
                        );
                    } catch (FileException $e) {
                        // ... handle exception if something happens during file upload
                    }

                    $article->setThumbnailImg($newfn);
                }
            }
            $article->setSlug(str_replace(' ','-',$article->getTitle()));
            $article->setCreatedAt(new \DateTime());
            $article->setViews(0);
            $article->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('articles_index');
        }

        return $this->render('articles/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="articles_show", methods={"GET"})
     */
    public function show(Articles $article): Response
    {
        return $this->render('articles/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="articles_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Articles $article): Response
    {
        $lastImg = $article->getThumbnailImg();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $img = $article->getThumbnailImg();
            if($img)
            {
                $newfn = $img->getClientOriginalName();
                try {
                    $img->move(
                        $this->getParameter('bibliotheque'),
                        $newfn
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $article->setThumbnailImg($newfn);
            }else{
                $article->setThumbnailImg($lastImg);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('articles_index');
        }

        return $this->render('articles/edit.html.twig', [
            'article' => $article,
            'lastImg'=>$lastImg,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="articles_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Articles $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('articles_index');
    }
}

templates/articles/_delete_form.html.twig
<form method="post" action="{{ path('articles_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger w-100">Supprimer</button>
</form>

templates/articles/_form.html.twig
{{ form_start(form) }}
    <div class="card">
        <div class="card-header card-header-primary">
            {{ title|default('title') }}
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6 text-center">
                    <div class="fileinput fileinput-new text-center" data-provides="fileinput">
                        <div class="fileinput-new thumbnail img-raised">
                            <img src="{% if lastImg is defined %}{{ asset('assets/allImg/'~lastImg) }}{% else %}{{ asset('assets/dashboard/img/image_placeholder.jpg') }}{% endif %}" alt="...">
                        </div>
                        <div class="fileinput-preview fileinput-exists thumbnail img-raised"></div>
                        <div>
        <span class="btn btn-raised btn-round btn-default btn-file">
            <span class="fileinput-new">{{ form_label(form.thumbnail_img) }}</span>
            {{ form_widget(form.thumbnail_img) }}
            <span class="fileinput-exists">{{ form_label(form.thumbnail_img) }}</span>
        </span>
                            <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                        </div>
                    </div>

                </div>
                <div class="col-md-6">
                    {{ form_errors(form.title) }}
                    {{ form_errors(form.description) }}
                    {{ form_errors(form.Category) }}
                    {{ form_errors(form.body) }}
                    <div class="form-group">
                        <label>Titre de l'article</label>
                        {{ form_widget(form.title) }}
                    </div>
                    <div class="form-group">
                        <label>Catégorie</label>
                        {{ form_widget(form.Category) }}
                    </div>
                    <div class="form-group">
                        <label>Description</label>
                        {{ form_widget(form.description) }}
                    </div>
                </div>
                <div class="col-md-12">
                        <label>Contenu de l'article</label>
                        {{ form_widget(form.body) }}
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
                <a href="{{ path('articles_index') }}" class="btn btn-primary">Retour</a>
            </div>
        </div>
    </div>
{{ form_end(form) }}

templates/articles/edit.html.twig
{% extends 'back/base.html.twig' %}
{% block css %}
    <link rel="stylesheet" href="{{ asset('assets/vendors/summernote/dist/summernote-lite.css') }}">
{% endblock %}
{% block title %}Modification article{% endblock %}

{% block body %}
    {{ include('articles/_form.html.twig', {'button_label': 'Modifier'}) }}
    {{ include('articles/_delete_form.html.twig') }}
{% endblock %}
    {% block js %}
        <script src="https://cdn.tiny.cloud/1/asa3dbsz0r9ojprv7ck135v4gc3nmyyh2lrwaqs5iuxnae3q/tinymce/5/tinymce.min.js"></script>
        <script src="{{ asset('assets/vendors/summernote/dist/summernote-lite.js') }}"></script>
        <script>
            $('#articles_body').summernote({
                height: 100,
                focus: false,
            });
        </script>
    {% endblock %}

templates/articles/index.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
{% endblock %}
{% block body %}
    <div class="card">
        <div class="card-header card-header-primary">
            <h4>Articles</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="articles">
                    <thead>
                    <tr>
                        <th>Miniature</th>
                        <th>Date de création</th>
                        <th>Titre</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for article in articles %}
                        <tr>
                            <td><img src="{{ asset('assets/allImg/'~article.thumbnailImg) }}" alt="Miniature" width="50"></td>
                            <td>{{ article.createdAt ? article.createdAt|date('Y-m-d') : '' }}</td>
                            <td>{{ article.title }}</td>
                            <td>
                                <a href="{{ path('articles_show', {'id': article.id}) }}" class="btn btn-primary">Voir</a>
                                <a href="{{ path('articles_edit', {'id': article.id}) }}" class="btn btn-warning">Modifier</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="8">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="card-footer">
                <a href="{{ path('articles_new') }}" class="btn btn-primary">Ajouter</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#articles').DataTable( {
                "language": {
                    "url":"//cdn.datatables.net/plug-ins/1.10.20/i18n/French.json"
                }
            } );
        } );
    </script>
{% endblock %}

templates/articles/new.html.twig
{% extends 'back/base.html.twig' %}
{% block css %}
    <link rel="stylesheet" href="{{ asset('assets/vendors/summernote/dist/summernote-lite.css') }}">
{% endblock %}
{% block title %}Nouvel article{% endblock %}

{% block body %}
    {{ include('articles/_form.html.twig',{'title':'Nouvel article'}) }}


{% endblock %}
{% block js %}
    <script src="{{ asset('assets/vendors/summernote/dist/summernote-lite.js') }}"></script>
    <script>
        $('#articles_body').summernote({
            height: 100,
            focus: false,
        });
    </script>
{% endblock %}

templates/articles/show.html.twig
{% extends 'back/base.html.twig' %}

{% block title %}Articles{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header card-header-primary">
            <h4>{{ article.title }}</h4>

        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <img src="{{ asset('assets/allImg/'~ article.thumbnailImg) }}" class="w-100 img-fluid" alt="miniature">
                </div>
                <div class="col-md-6">
                    <hr>
                    <div>
                        <h4 class="text-primary">Date de création</h4>
                        <p>{{ article.createdAt ? article.createdAt|date('Y-m-d') : '' }}</p>
                    </div>
                    <hr>
                    <div>
                        <h4 class="text-primary">Titre</h4>
                        <p>{{ article.title }}</p>
                    </div>
                    <hr>
                    <div>
                        <h4 class="text-primary">Description</h4>
                        <p>{{ article.description }}</p>
                    </div>
                    <hr>
                    <div>
                        <h4 class="text-primary">Catégorie</h4>
                        <p>{{ article.category.name }}</p>
                    </div>
                    <hr>
                    <div>
                        <h4 class="text-primary">Nombre de vues</h4>
                        <p>{{ article.views }}</p>
                    </div>
                    <div>
                        <h4 class="text-primary">Créateur</h4>
                        <p><a href="{{ path('user_show',{'id':article.user.id}) }}">{{ article.user.username }}</a></p>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr>
                    <div>
                        <h4 class="text-primary">Contenu de l'article</h4>
                        <p>{{ article.body|raw }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="{{ path('articles_index') }}" class="btn btn-primary">Retour</a>

                <a href="{{ path('articles_edit', {'id': article.id}) }}" class="btn btn-warning">Modifier</a>

                {{ include('articles/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}